name: CI/CD Pipeline for Dockerized Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build Docker containers
    - name: Build Docker Images
      run: |
        docker-compose -f docker-compose.yaml up --build -d

    # Step 4: Run tests inside the container
    - name: Run Tests
      run: |
        docker exec <container_name> /bin/bash -c "pytest tests/"

    # Step 5: Tear down containers
    - name: Teardown Docker Containers
      if: always()
      run: |
        docker-compose -f docker-compose.yaml down
